### ISSUE TITLE
Uncaught Error: listen EADDRINUSE null:8001

### ISSUE THREAD

**Issue by sMaDyK** [joeferraro/MavensMate-Atom#140] opened 2015-02-05 15:44 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.15

### Stack Trace

Uncaught Error: listen EADDRINUSE null:8001

```
At events.js:94

Error: listen EADDRINUSE null:8001
  at Object.exports._errnoException (util.js:753:11)
  at exports._exceptionWithHostPort (util.js:776:20)
  at Server._listen2 (net.js:1155:14)
  at listen (net.js:1181:10)
  at Server.listen (net.js:1268:5)
  at UIServer.startServer (C:\Users\XXX\.atom\packages\MavensMate-Atom\node_modules\mavensmate\lib\mavensmate\ui\server.js:284:19)
  at C:\Users\XXX\.atom\packages\MavensMate-Atom\node_modules\mavensmate\lib\mavensmate\ui\server.js:57:12
  at Server.onListen (C:\Users\XXX\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\portfinder\lib\portfinder.js:48:5)
  at Server.g (events.js:202:16)
  at Server.emit (events.js:113:17)
  at net.js:1170:12
  at process._tickCallback (node.js:364:11)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "MavensMate-Atom": {
    "mm_workspace": [
      "D:\\SalesForce\\Mavensmate\\ATOM workspace"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.15

# Dev
No dev packages
```

/cc @atom/core

**Comment by joeferraro** [comment] 2015-02-13 15:46
duplicate of https://github.com/joeferraro/MavensMate-Atom/issues/120

**Closed by joeferraro** 2015-02-13 15:46 UTC
