### ISSUE TITLE
"Conflict Detected" when no conflict exists

### ISSUE THREAD

**Issue by mh2292** [joeferraro/MavensMate-Atom#178] opened 2015-03-31 17:28 UTC
The following error is displayed when no conflict exists between the server and local copy. This often occurs even when the server copy hasn't been modified. 
"A conflict has been detected between the local and server copy. Please refresh the metadata from server to continue."

**Comment by joeferraro** [comment] 2015-03-31 17:31
duplicate of https://github.com/joeferraro/MavensMate-Atom/issues/148, please search before submitting new issues

**Closed by joeferraro** 2015-03-31 17:31 UTC
