### ISSUE TITLE
Uncaught Error: listen EADDRINUSE :::8000

### ISSUE THREAD

**Issue by venkatpolisetti** [joeferraro/MavensMate-Atom#201] opened 2015-06-07 16:51 UTC
Installed latest version of Mavensmate for IOS. Still getting this error:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.22

### Stack Trace

Uncaught Error: listen EADDRINUSE :::8000

```
At events.js:141

Error: listen EADDRINUSE :::8000
  at Object.exports._errnoException (util.js:734:11)
  at exports._exceptionWithHostPort (util.js:757:20)
  at Server._listen2 (net.js:1173:14)
  at listen (net.js:1203:10)
  at Server.listen (net.js:1290:5)
  at UIServer.startServer (/Users/venkatpolisetti/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/server.js:290:19)
  at /Users/venkatpolisetti/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/server.js:63:12
  at Server.onListen (/Users/venkatpolisetti/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/portfinder/lib/portfinder.js:48:5)
  at Server.g (events.js:257:16)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:163:7)
  at net.js:1192:12
  at process._tickCallback (node.js:357:13)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "MavensMate-Atom": {
    "mm_workspace": [
      "/Users/venkatpolisetti/Documents/mavensmate/atom"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.22
atom-alignment, v0.12.1
auto-reveal-in-sidebar, v0.5.0
change-case, v0.6.0
emmet, v2.3.10
jshint, v1.3.7
language-salesforce, v0.6.0
minimap, v4.9.4
vim-mode, v0.51.0

# Dev
No dev packages
```

**Comment by joeferraro** [comment] 2015-06-07 17:23
duplicate of https://github.com/joeferraro/MavensMate-Atom/issues/120

**Closed by joeferraro** 2015-06-07 17:23 UTC
