### ISSUE TITLE
Uncaught Error: listen EADDRINUSE :::8002

### ISSUE THREAD

**Issue by kitaarashi** [joeferraro/MavensMate-Atom#192] opened 2015-05-09 08:31 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.20

### Stack Trace

Uncaught Error: listen EADDRINUSE :::8002

```
At events.js:141

Error: listen EADDRINUSE :::8002
  at Object.exports._errnoException (util.js:734:11)
  at exports._exceptionWithHostPort (util.js:757:20)
  at Server._listen2 (net.js:1173:14)
  at listen (net.js:1203:10)
  at Server.listen (net.js:1290:5)
  at UIServer.startServer (/Users/kitaarashi/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/server.js:290:19)
  at /Users/kitaarashi/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/server.js:63:12
  at Server.onListen (/Users/kitaarashi/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/portfinder/lib/portfinder.js:48:5)
  at Server.g (events.js:257:16)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:163:7)
  at net.js:1192:12
  at process._tickCallback (node.js:357:13)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "projectHome": "/Users/kitaarashi/MyData/atom_workspace/"
  },
  "MavensMate-Atom": {
    "mm_workspace": [
      "/Users/kitaarashi/MyData/atom_workspace/"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.20
autoclose-html, v0.15.0
file-icons, v1.5.5
pretty-json, v0.3.3

# Dev
No dev packages
```

**Comment by motiko** [comment] 2015-05-15 12:57
It means the port is in use. Validate you are not running a process which utlizes the same port as mm (maybe another instance of MavensMate is running in other editor? )

**Comment by joeferraro** [comment] 2015-06-07 16:20
duplicate of #120

**Closed by joeferraro** 2015-06-07 16:20 UTC
