### ISSUE TITLE
Uncaught Error: ENOTEMPTY, directory not empty 'c:\Users\admin\mm_workspace\myorg\unpackaged\staticresources'

### ISSUE THREAD

**Issue by rnalla** [joeferraro/MavensMate-Atom#137] opened 2015-02-03 13:15 UTC
[Enter steps to reproduce below:]

1. Create New Project

**Atom Version**: 0.175.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.15

### Stack Trace

Uncaught Error: ENOTEMPTY, directory not empty 'c:\Users\admin\mm_workspace\myorg\unpackaged\staticresources'

```
At c:\Users\admin\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\async.js:103

Error: ENOTEMPTY, directory not empty 'c:\Users\admin\mm_workspace\myorg\unpackaged\staticresources'
  at Error (native)
  at Object.fs.rmdirSync (fs.js:649:18)
  at rmkidsSync (c:\Users\admin\AppData\Local\atom\app-0.175.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:247:11)
  at rmdirSync (c:\Users\admin\AppData\Local\atom\app-0.175.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:237:7)
  at fixWinEPERMSync (c:\Users\admin\AppData\Local\atom\app-0.175.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:150:5)
  at rimrafSync (c:\Users\admin\AppData\Local\atom\app-0.175.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:216:26)
  at c:\Users\admin\AppData\Local\atom\app-0.175.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:245:5
  at Array.forEach (native)
  at rmkidsSync (c:\Users\admin\AppData\Local\atom\app-0.175.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:244:26)
  at rmdirSync (c:\Users\admin\AppData\Local\atom\app-0.175.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:237:7)
  at fixWinEPERMSync (c:\Users\admin\AppData\Local\atom\app-0.175.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:150:5)
  at rimrafSync (c:\Users\admin\AppData\Local\atom\app-0.175.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:216:26)
  at c:\Users\admin\AppData\Local\atom\app-0.175.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:245:5
  at Array.forEach (native)
  at rmkidsSync (c:\Users\admin\AppData\Local\atom\app-0.175.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:244:26)
  at rmdirSync (c:\Users\admin\AppData\Local\atom\app-0.175.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:237:7)
  at fixWinEPERMSync (c:\Users\admin\AppData\Local\atom\app-0.175.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:150:5)
  at Function.rimrafSync (c:\Users\admin\AppData\Local\atom\app-0.175.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:216:26)
  at Object.rmrfSync (c:\Users\admin\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\fs-extra\lib\remove.js:7:19)
  at c:\Users\admin\.atom\packages\MavensMate-Atom\node_modules\mavensmate\lib\mavensmate\project.js:351:16
  at tryCatch1 (c:\Users\admin\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\util.js:45:21)
  at Promise._callHandler (c:\Users\admin\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:571:13)
  at Promise._settlePromiseFromHandler (c:\Users\admin\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:581:18)
  at Promise._settlePromiseAt (c:\Users\admin\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:733:18)
  at Promise._settlePromises (c:\Users\admin\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:845:14)
  at Async._consumeFunctionBuffer (c:\Users\admin\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\async.js:85:12)
  at Async.consumeFunctionBuffer (c:\Users\admin\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\async.js:40:14)
  at process._tickCallback (node.js:386:11)

```

### Commands

```
     -30:03.5 mavensmate:open-project (atom-text-editor.editor)
     -30:00.0 mavensmate:new-project (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {},
  "MavensMate-Atom": {
    "mm_workspace": [
      "C:/Users/admin/mm_workspace"
    ],
    "mm_default_subscription": [
      "ApexTrigger"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.15

# Dev
No dev packages
```

/cc @atom/core

**Comment by joeferraro** [comment] 2015-02-06 15:06
duplicate of https://github.com/joeferraro/MavensMate-Atom/issues/125

**Closed by joeferraro** 2015-02-06 15:06 UTC
Labels: bug
