### ISSUE TITLE
Uncaught Error: ENOTEMPTY, directory not empty 'C:\Users\User\workspace\atom\AM VR\unpackaged\staticresources'

### ISSUE THREAD

**Issue by hubsonx** [joeferraro/MavensMate-Atom#141] opened 2015-02-06 14:46 UTC
[Enter steps to reproduce below:]

1. Fresh installation Atom + MavensMate 0.15
2. Fresh workspace directory set (empty)
3. Create new project (just credentials provided, standard settings)

**Atom Version**: 0.177.0
**System**: Unknown Windows Version
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.15

### Stack Trace

Uncaught Error: ENOTEMPTY, directory not empty 'C:\Users\User\workspace\atom\AM VR\unpackaged\staticresources'

```
At C:\Users\User\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\async.js:103

Error: ENOTEMPTY, directory not empty 'C:\Users\User\workspace\atom\AM VR\unpackaged\staticresources'
  at Error (native)
  at Object.fs.rmdirSync (fs.js:716:18)
  at rmkidsSync (C:\Users\User\AppData\Local\atom\app-0.177.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:247:11)
  at rmdirSync (C:\Users\User\AppData\Local\atom\app-0.177.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:237:7)
  at fixWinEPERMSync (C:\Users\User\AppData\Local\atom\app-0.177.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:150:5)
  at rimrafSync (C:\Users\User\AppData\Local\atom\app-0.177.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:216:26)
  at C:\Users\User\AppData\Local\atom\app-0.177.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:245:5
  at Array.forEach (native)
  at rmkidsSync (C:\Users\User\AppData\Local\atom\app-0.177.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:244:26)
  at rmdirSync (C:\Users\User\AppData\Local\atom\app-0.177.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:237:7)
  at fixWinEPERMSync (C:\Users\User\AppData\Local\atom\app-0.177.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:150:5)
  at rimrafSync (C:\Users\User\AppData\Local\atom\app-0.177.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:216:26)
  at C:\Users\User\AppData\Local\atom\app-0.177.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:245:5
  at Array.forEach (native)
  at rmkidsSync (C:\Users\User\AppData\Local\atom\app-0.177.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:244:26)
  at rmdirSync (C:\Users\User\AppData\Local\atom\app-0.177.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:237:7)
  at fixWinEPERMSync (C:\Users\User\AppData\Local\atom\app-0.177.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:150:5)
  at Function.rimrafSync (C:\Users\User\AppData\Local\atom\app-0.177.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:216:26)
  at Object.rmrfSync (C:\Users\User\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\fs-extra\lib\remove.js:7:19)
  at C:\Users\User\.atom\packages\MavensMate-Atom\node_modules\mavensmate\lib\mavensmate\project.js:351:16
  at tryCatch1 (C:\Users\User\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\util.js:45:21)
  at Promise._callHandler (C:\Users\User\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:571:13)
  at Promise._settlePromiseFromHandler (C:\Users\User\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:581:18)
  at Promise._settlePromiseAt (C:\Users\User\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:733:18)
  at Promise._settlePromises (C:\Users\User\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:845:14)
  at Async._consumeFunctionBuffer (C:\Users\User\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\async.js:85:12)
  at Async.consumeFunctionBuffer (C:\Users\User\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\async.js:40:14)
  at process._tickCallback (node.js:364:11)

```

### Commands

```
     -1:01.0 mavensmate:new-project (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "MavensMate-Atom": {
    "mm_workspace": [
      "C:\\Users\\User\\workspace\\atom"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.15

# Dev
No dev packages
```

/cc @atom/core

**Comment by joeferraro** [comment] 2015-02-06 15:05
thanks, this is a known issue on windows duplicate of https://github.com/joeferraro/MavensMate-Atom/issues/137 and https://github.com/joeferraro/MavensMate-Atom/issues/136

**Closed by joeferraro** 2015-02-06 15:05 UTC
