### ISSUE TITLE
Uncaught Error: listen EADDRINUSE :::8001

### ISSUE THREAD

**Issue by tak4hir0** [joeferraro/MavensMate-Atom#191] opened 2015-05-07 20:18 UTC
[Enter steps to reproduce below:]

1. open atom
2. new tab

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.20

### Stack Trace

Uncaught Error: listen EADDRINUSE :::8001

```
At events.js:141

Error: listen EADDRINUSE :::8001
  at Object.exports._errnoException (util.js:734:11)
  at exports._exceptionWithHostPort (util.js:757:20)
  at Server._listen2 (net.js:1173:14)
  at listen (net.js:1203:10)
  at Server.listen (net.js:1290:5)
  at UIServer.startServer (/Users/tak4hir0/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/server.js:290:19)
  at /Users/tak4hir0/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/ui/server.js:63:12
  at Server.onListen (/Users/tak4hir0/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/portfinder/lib/portfinder.js:48:5)
  at Server.g (events.js:257:16)
  at emitNone (events.js:67:13)
  at Server.emit (events.js:163:7)
  at net.js:1192:12
  at process._tickCallback (node.js:357:13)

```

### Commands

```
```

### Config

```json
{
  "core": {},
  "MavensMate-Atom": {
    "mm_workspace": [
      "/Users/tak4hir0/Documents/Workspace/Atom/"
    ],
    "mm_panel_height": 115
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.20

# Dev
No dev packages
```

**Comment by joeferraro** [comment] 2015-06-07 16:20
duplicate of #120

**Closed by joeferraro** 2015-06-07 16:20 UTC
