### ISSUE TITLE
Does not retrieve lighting components from the org

### ISSUE THREAD

**Issue by nkint** [joeferraro/MavensMate-Atom#186] opened 2015-04-24 14:40 UTC
Hi!
I'm on windows, just downloaded atom and mavensmate

I have an org where I have already created some lighting test things (one app, two components with respective controller helper etc) but they are not dowloaded from the org.

Moreover, if I try to create a new fresh lighting component on atom-mavensmate it creates only the .cmp while che checkbox for helper controller renderer are checked.

Any info on that please?

**Comment by nkint** [comment] 2015-04-24 14:49
Tested also on linux Arch, same problem...

**Comment by ThomasSFDC** [comment] 2015-06-24 14:18
Same problem on Mac. When creating a new Lightning Component it creates only the .cmp even when the checkboxes for helper, controller, etc are checked. Seems to be no way to reach the controller, helper etc as only the .cmp shows up in the project directory tree

**Comment by nelsonra** [comment] 2015-07-01 11:52
I'm not sure if I have a similar issue (sorry if this isn't related I'll create a new issue). I'm only trying this plugin and atom out for the first time today so I'm a complete newbie.

My issue (sounds similar) : I can connect with Mavensmate to my dev org and download the resources except for my lightning resources. 

Reproduce : 
- Connect to an existing dev org with both lightning and apex files.
- In the project metadata tab of the project settings, I check the box "AuraDefinitionBundle" and update my project I get this error : "Could not extract and write stream to file system."

Any help appreciated. Thanks

**Comment by nelsonra** [comment] 2015-07-02 12:45
Update : I tried manually editing the package.xml to have only the AuraBundle:

<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>AuraDefinitionBundle</name>
    </types>
    <version>33.0</version>
</Package>

Here is the full error:

> Cleaning project
> Could not clean project
{
  "result": "Could not clean project",
  "error": "Could not extract and write stream to file system.",
  "stack": "Error: Could not extract and write stream to file system.\n  at /Users/nelson/.atom/packages/MavensMate-Atom/node_modules/mavensmate/lib/mavensmate/util.js:331:35\n  at tryCatcher (/Users/nelson/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/fs-extra-promise/node_modules/bluebird/js/main/util.js:24:31)\n  at Promise._settlePromiseFromHandler (/Users/nelson/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/fs-extra-promise/node_modules/bluebird/js/main/promise.js:454:31)\n  at Promise._settlePromiseAt (/Users/nelson/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/fs-extra-promise/node_modules/bluebird/js/main/promise.js:530:18)\n  at Promise._settlePromises (/Users/nelson/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/fs-extra-promise/node_modules/bluebird/js/main/promise.js:646:14)\n  at Async._drainQueue (/Users/nelson/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/fs-extra-promise/node_modules/bluebird/js/main/async.js:182:16)\n  at Async._drainQueues (/Users/nelson/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/fs-extra-promise/node_modules/bluebird/js/main/async.js:192:10)\n  at MutationObserver.Async.drainQueues (/Users/nelson/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/fs-extra-promise/node_modules/bluebird/js/main/async.js:15:14)\n",
  "promiseId": "fc2a6910-20b7-11e5-b139-9b708a586dca"
}

**Comment by joeferraro** [comment] 2015-09-22 04:30
this should be resolved in v1.0.0. please feel free to re-open if you're still experiencing this issue. thanks!

**Comment by thvd** [comment] 2015-09-22 10:00
Today I updated Mavensmate for Atom to the latest version, and got the same error.

**Comment by joeferraro** [comment] 2015-09-22 12:41
@thvd do you only have this problem with lightning components or is it any type of metadata? 

If this is affecting any type of metadata, is the `unzip` executable installed and accessible on your PATH?

**Comment by thvd** [comment] 2015-09-22 13:45
@joeferraro: it's not specific to any type of metadata. 

And yes, `unzip` is in my PATH variable:
```

theodoor@theodoor-XPS-15-9530:/usr/bin$ unzip
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.


```

**Comment by joeferraro** [comment] 2015-09-22 13:49
@thvd can you do me a favor and configure your mavensmate-app log level to SILLY and post any relevant logs?

**Comment by joeferraro** [comment] 2015-09-22 13:50
@thvd also, which Linux distro are you running?

**Comment by e02d96ec16** [comment] 2015-10-02 17:07
I had the same issue: MM 0.0.8, Win 7 Pro.

```json
{
  "id": "cd0d31f0-6912-11e5-865e-df917cd88d48",
  "complete": true,
  "error": "Could not extract and write stream to file system.",
  "stack": 
  	"Error: Could not extract and write stream to file system.
  	    at C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\lib\\mavensmate\\util.js:389:37
  	        at tryCatcher (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\util.js:26:23)
  	           at Promise._settlePromiseFromHandler (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\promise.js:503:31)
  	               at Promise._settlePromiseAt (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\promise.js:577:18)
  	                   at Promise._settlePromises (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\promise.js:693:14)
  	                       at Async._drainQueue (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\async.js:123:16)
  	                           at Async._drainQueues (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\async.js:133:10)
  	                               at Immediate.Async.drainQueues [as _onImmediate] (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\async.js:15:14)
  	                                   at processImmediate [as _immediateCallback] (timers.js:371:17)"
}
```

Set the debug level to __SILLY__ and found:

```log
debug: cscriptExe is:  cscript
error: error retrieving and writing to disk
error: Could not extract and write stream to file system.
error: Could not index metadata type CustomObject: Could not extract and write stream to file system.
error: Error: Could not extract and write stream to file system.
```

Trying to run the command said:

 ```batchfile
PS C:\Windows\system32> cscript
CScript Error: Windows Script Host access is disabled on this machine. Contact your administrator for details.
```

Enabled WHS by switching the registry value to 1:

```reg
[HKEY_CURRENT_USER\Software\Microsoft\Windows Script Host\Settings]
"Enabled"=dword:00000001
```

Platform | Solution
------------|----------------
![win7pro](https://cloud.githubusercontent.com/assets/14942417/10252125/50000424-692d-11e5-95f9-c3e566700a7e.png) | [Windows Script Host](https://en.wikipedia.org/wiki/Windows_Script_Host) needs to be enabled. Import [this registry file](https://gist.github.com/e02d96ec16/856995b402b7638eb26f#file-enablewhs-reg) or do it manually.

**Comment by thvd** [comment] 2015-10-06 13:24
@joeferraro, I'm running Ubuntu 15.04. But I cannot reproduce the error anymore. I 'fixed' the issue by removing another clone of the org I had. So I think the error comes from the fact that I had two projects in one folder, with the same Mavensmate 'Name'.

**Closed** 2016-09-19 12:46 UTC
Labels: more-information-needed
