### ISSUE TITLE
Uncaught Error: ENOTEMPTY, directory not empty 'c:\Users\John.Harcourt\Documents\MavensMate\Salesforce\axDev\unpackaged\classes'

### ISSUE THREAD

**Issue by indyHarcourt** [joeferraro/MavensMate-Atom#136] opened 2015-02-02 22:14 UTC
1.  On MavensMate settings, typed in "ApexClass" for Mm default subscription
2.  Selected MavensMate > Project > New Project
3. Typed in Project Details.  
     ---> This ought to be clear about entering password/security token
4. Clicked on "Refresh" button
5. The "Project Metadata" tab became active. I expanded the "ApexClass" tree and selected one class.
   ---> There is nothing here that makes it clear what to do next. Click on Refresh? No, that just refreshes the tree and unchecks any selections I had made. There are no instructions nor is there an "OK" button. The "Create Project" button is present for all the tabs, so it isn't clear that's what to click next.

6. Clicked the "Create Project" button. 

I then immediately received the below error.  
[My project name is AxDev.]

Note that my project directory was not present before I started. It created the AxDev/unpackaged/classes folders.  In the "unpackaged" folder is a "package.xml" file. Nothing is in the "classes" folder.
Thanks!
-----

**Atom Version**: 0.176.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v0.0.15

### Stack Trace

Uncaught Error: ENOTEMPTY, directory not empty 'c:\Users\John.Harcourt\Documents\MavensMate\Salesforce\axDev\unpackaged\classes'

```
At c:\Users\John.Harcourt\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\async.js:103

Error: ENOTEMPTY, directory not empty 'c:\Users\John.Harcourt\Documents\MavensMate\Salesforce\axDev\unpackaged\classes'
  at Error (native)
  at Object.fs.rmdirSync (fs.js:649:18)
  at rmkidsSync (c:\Users\John.Harcourt\AppData\Local\atom\app-0.176.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:247:11)
  at rmdirSync (c:\Users\John.Harcourt\AppData\Local\atom\app-0.176.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:237:7)
  at fixWinEPERMSync (c:\Users\John.Harcourt\AppData\Local\atom\app-0.176.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:150:5)
  at rimrafSync (c:\Users\John.Harcourt\AppData\Local\atom\app-0.176.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:216:26)
  at c:\Users\John.Harcourt\AppData\Local\atom\app-0.176.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:245:5
  at Array.forEach (native)
  at rmkidsSync (c:\Users\John.Harcourt\AppData\Local\atom\app-0.176.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:244:26)
  at rmdirSync (c:\Users\John.Harcourt\AppData\Local\atom\app-0.176.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:237:7)
  at fixWinEPERMSync (c:\Users\John.Harcourt\AppData\Local\atom\app-0.176.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:150:5)
  at rimrafSync (c:\Users\John.Harcourt\AppData\Local\atom\app-0.176.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:216:26)
  at c:\Users\John.Harcourt\AppData\Local\atom\app-0.176.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:245:5
  at Array.forEach (native)
  at rmkidsSync (c:\Users\John.Harcourt\AppData\Local\atom\app-0.176.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:244:26)
  at rmdirSync (c:\Users\John.Harcourt\AppData\Local\atom\app-0.176.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:237:7)
  at fixWinEPERMSync (c:\Users\John.Harcourt\AppData\Local\atom\app-0.176.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:150:5)
  at Function.rimrafSync (c:\Users\John.Harcourt\AppData\Local\atom\app-0.176.0\resources\app\node_modules\fs-plus\node_modules\rimraf\rimraf.js:216:26)
  at Object.rmrfSync (c:\Users\John.Harcourt\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\fs-extra\lib\remove.js:7:19)
  at c:\Users\John.Harcourt\.atom\packages\MavensMate-Atom\node_modules\mavensmate\lib\mavensmate\project.js:351:16
  at tryCatch1 (c:\Users\John.Harcourt\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\util.js:45:21)
  at Promise._callHandler (c:\Users\John.Harcourt\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:571:13)
  at Promise._settlePromiseFromHandler (c:\Users\John.Harcourt\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:581:18)
  at Promise._settlePromiseAt (c:\Users\John.Harcourt\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:733:18)
  at Promise._settlePromises (c:\Users\John.Harcourt\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:845:14)
  at Async._consumeFunctionBuffer (c:\Users\John.Harcourt\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\async.js:85:12)
  at Async.consumeFunctionBuffer (c:\Users\John.Harcourt\.atom\packages\MavensMate-Atom\node_modules\mavensmate\node_modules\bluebird\js\main\async.js:40:14)
  at process._tickCallback (node.js:386:11)

```

### Commands

```
     -8:01.3 mavensmate:new-project (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "MavensMate-Atom": {
    "mm_workspace": [
      "C:\\Users\\John.Harcourt\\Documents\\MavensMate\\Salesforce"
    ],
    "mm_default_subscription": [
      "ApexClass"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-csharp, v0.3.0
MavensMate-Atom, v0.0.15

# Dev
No dev packages
```

/cc @atom/core

**Comment by joeferraro** [comment] 2015-02-06 15:07
duplicate of https://github.com/joeferraro/MavensMate-Atom/issues/125

**Closed by joeferraro** 2015-02-06 15:07 UTC
