### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by RonnieStepOrange** [joeferraro/MavensMate-Atom#204] opened 2015-06-08 09:11 UTC
Hi,

Since the upgrade to 0.0.22 I get the following error when loading a project.

Could not activate MavensMate project. MavensMate will not function correctly.
undefined is not a function.

Regards, Ronnie

**Comment by thvd** [comment] 2015-06-08 09:25
Duplicate of: #203

**Comment by thvd** [comment] 2015-06-08 09:26
You can run atom as `atom --include-deprecated-apis .`, than the error will disappear.

**Comment by RonnieStepOrange** [comment] 2015-06-08 09:41
were do I put that?

**Comment by thvd** [comment] 2015-06-08 10:12
You have to start Atom via the command line to use that solution.

**Closed** 2015-06-08 13:13 UTC
